1. What is a Python library? Why do we use Python libraries?

Soln 1. Pyhton libraraies are the pre-written code that can be used repeatedly in different programs.

We use python libraries because :
*   It is efficient.
*   Readability
*   Huge numbers of Libraries
*   Reusability
*   Can perform multiple task in easier way

2. What is the difference between Numpy array and List?

Soln 2. The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a mixture of strings, numbers, booleans and other objects.

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(f"Shape: {arr.shape}")
print(f"Size: {arr.size}")
print(f"Dimension: {arr.ndim}")

Shape: (3, 4)
Size: 12
Dimension: 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(f"First Row : ",arr[0])

First Row :  [1 2 3 4]


5. How do you access the element at the third row ana fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print("Element at 3rd Row and 4th Column : ",arr[2][3])

Element at 3rd Row and 4th Column :  12


6. Write code to extract all odd indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("all odd indexed elements from the given numpy array are : ",arr[:, ::2])

all odd indexed elements from the given numpy array are :  [[ 1  3]
 [ 5  7]
 [ 9 11]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [ ]:
import numpy as np
matrix = np.random.rand(3, 3)
print(matrix)

[[0.16052015 0.9097502  0.95783645]
 [0.89757296 0.41844587 0.0853042 ]
 [0.77004233 0.63256869 0.58555778]]


8. Describe the difference between np.random.rand and np.random.randn?

* np.random.rand: generates uniformly distributed random numbers in the half-open
interval [0, 1). This means each number within that range has an equal probability of being generated.

* np.random.randn: generates normally distributed random numbers with a mean of 0 and a standard deviation of 1. This means most of the generated numbers will be clustered around 0, with progressively fewer numbers occurring the further they are from 0.

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
arr1=np.reshape(arr,(6,2))
print("New Array : ",arr1)
print("Shape of array : ",arr1.shape)

New Array :  [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Shape of array :  (6, 2)


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
transposeArray=arr.transpose()
print("Transpose of array : ",transposeArray)

Transpose of array :  [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python
* Index wise multiplication
* Matix multiplication
* Add both the matics
* Subtact matix B from A
* Divide Matix B by A

In [ ]:
import numpy as np
A = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
B = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

#Index Wise Multiplication
C = A * B
print("Result of element-wise multiplication:",C)

#Add both the matics
Add=A+B
print("Addition of 2 matrix is : ",Add )

#Subtact matix B from A
Sub=A-B
print("Subtraction of 2 matrix is : ",Sub )

#Divide Matix B by A
Div=B/A
print("Division of Mtrix B by A is : ",Div)

Result of element-wise multiplication: [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Addition of 2 matrix is :  [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction of 2 matrix is :  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division of Mtrix B by A is :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

matrix_product = np.dot(A, B)
matrix_product

array([[19, 22],
       [43, 50]])

12. Which function in Numpy can be used to swap the byte order of an array?


Soln 12. The function in NumPy to swap the byte order of an array is byteswap().

In [ ]:
import numpy as np

arr = np.array([0x1234, 0x5678])
swapped_arr = arr.byteswap()

print("Original array:", arr)
print("Swapped array:", swapped_arr)  # Output: [16962 9252]

Original array: [ 4660 22136]
Swapped array: [3752061439553044480 8671118132548468736]


13. What is the significance of the np.linalg.inv function?


Soln 13. The function numpy.linalg.inv() is available in the NumPy module ,it is used to compute the inverse matrix in Python

In [3]:
import numpy as np
A = np.array([[6, 1, 1, 3],
              [4, -2, 5, 1],
              [2, 8, 7, 6],
              [3, 1, 9, 7]])

print(np.linalg.inv(A))

[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]


14. What does the np.reshape function do, and how is it used?

Soln 14. Reshaping means changing the shape of an array.

* The shape of an array is the number of elements in each dimension.

* By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


15. What is broadcasting in Numpy?

Soln 15. Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.